### ISSUE TITLE
Overview on the help page needs a "no data" state

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#106]
**Description**
The interactive react flow overview within the help page does not display any wallet addresses when viewed on a mobile device (test on both iOS and Android / Safari and Chrome enginers). 

**Steps To Reproduce**

1. Open Nova Wallet on Android or iOS
2. Navigate to Multix
3. Connect wallet
4. Open hamburger menu
5. Tap "Help"
6. Scroll down to the overview component

**Expected Behaviour**
Either the wallet addresses should be visible on mobile or we should hide this component when viewed on mobile. 

**Screenshots / Video**
![IMG_9674C6C695EF-1](https://user-images.githubusercontent.com/3982665/234663736-e7fdaf51-2ff8-4d83-b4fe-441baa2201db.jpeg)
![screenshot_20230426-103322_720](https://user-images.githubusercontent.com/3982665/234663740-bce9d4e2-fa3f-442b-b932-77f8a12d0dd5.png)

**Test Host Specifics: **
 - OS: iOS / Android (iPhone 14 Pro / Google Pixel 6 Pro)
 - Browser [Chrome / Safari within Nova wallet]
 - Version: 6.1
 - Wallet: Nova

**Additional context**
- Works fine when viewed on the dev tools in mobile layout, only an issue on real devices
- Doesn't seem to be an incorrect zoom level issue, nothing shown when scrolling around

**Comment by asnaith** [comment]
@Tbaut Actually, I've logged this in error - there were no multisigs on these accounts to display 😅. 

Perhaps a better no-data state is needed though?

**Comment by Tbaut** [comment]
Aaah nice, I selected a lob that manages am bile events on purpose. How did you see it without account?

**Comment by asnaith** [comment]
@Tbaut I had connected the wallet but not created a multisig and then just clicked on the "Help" navigation option (same on both desktop and mobile). 

So I think this original issue I logged is bogus but the actionable item here is perhaps to have a better no-data state, what do you think? 
<img width="1272" alt="Screenshot 2023-04-27 at 11 04 41 AM" src="https://user-images.githubusercontent.com/3982665/234953490-2d44ddb5-6430-4c82-9378-c27e0484ce8c.png">

**Comment by Tbaut** [comment]
Absolutely, will fix this.

**Comment by Tbaut** [comment]
We should actually simply hide the menu item when there's no multisig.

**Comment by Tbaut** [comment]
That's done
