### ISSUE TITLE
Send tx modal remove button is active when nothing to remove

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#131]
**Description**
The remove button is active when there's nothing to remove on the "Send TX" Modal. 

This is when the Batch transaction type is selected nd the pallet and method dropdowns appear. 

**Prerequisites**

Use an account that is already part of a multisig

**Steps To Reproduce**

Add clear steps on how to reproduce the bug

1. Go to Multix at 'https://multix.chainsafe.io/'
2. Click on the send icon on the home page
3. On the "Send TX" modal choose batch as the transaction type
4. Click the remove button and see it remove and recreate straight away 

**Expected Behaviour**
Until a pallet / method has been selected the remove button underneath the first extrinsic in the batch should be inactive. 

**Screenshots / Video**

<img width="902" alt="237236479-423a3949-afad-472c-b3ee-dc2ecbd9ede6" src="https://github.com/ChainSafe/Multix/assets/3982665/6b9c3091-1e7f-4400-9767-498f20522e41">

**Test Host Specifics: **
 - Not specific to any setup

**Additional context**

From a discussion on another PR: 

The first method/pallet is added by default, you need at least one otherwise it doesn't make sense as we discussed earlier. When you click on remove at this point, it's actually removed, ...and re-added right away. Checking for the pallet to have changed etc is too much small fiddling code for now (we are using the manual extrinsics component, the code is reused and the potential to create unmaintainable code is high) for me to add it as it'll change in the future. We can create an issue for this, it'll be low prio then and can be tackled when we have more time.

_Originally posted by @Tbaut in https://github.com/ChainSafe/Multix/issues/114#issuecomment-1541715610_

**Comment by Tbaut** [comment]
It may feel like a bug but it's actually working as intended: at any time, at least one extrinsic should be configurable. If you delete the only one, the UI will create and show it.

**Comment by Tbaut** [comment]
The "batch extrinsics" has been removed
