### ISSUE TITLE
Improve the ux of modal dismissal 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#132]
Modals are nicely dismissed when the user clicks outside of their display area but with batch transfers, this now increases the risk of causing user frustration if they accidentally dismiss a window they have populated with data. 

We should explore ways that protect the user from accidentally dismissing. 

This follows from a comment on a PR. Original comment: 

_Whilst crafting a transaction I had to switch between different apps and another browser to copy addresses. A few times when returning to the browser with multix, I clicked the window to activate it and accidentally clicked out of the modal which lost everything I was setting up for the batch transaction. Perhaps on this modal, we should have a confirmation in this context before closing the dialog? This has always been dismissable like this but could now potentially be a cause for user frustration if they were to lose long batched params that they've been in the middle of crafting._  

_Originally posted by @asnaith in https://github.com/ChainSafe/Multix/issues/114#issuecomment-1541013982_

**Comment by Tbaut** [comment]
I really really dislike popup asking "Are you sure blablabla" and I think this shows that something has been badly thought.
If we think that users don't land on a modal by mistake, meaning that they understood what they were clicking on to land here. Then it's very unlikely that they want to leave right away, as a result we can have the close behavior a little more complex to achieve than just a click outside. For consistency in the UI, we need all modals to behave the same as much as possible.

Therefor, I suggest that we don't close on click outset, and have either
- a close button
- a close cross at the top left

I'm thinking the first one is probably nicer, but the second one works better on mobile.

Any opinion?

**Comment by asnaith** [comment]
> I'm thinking the first one is probably nicer, but the second one works better on mobile.
> 
> Any opinion?

Agreed. A pop-up would look messy because the modal would already be stacked and another pop-up stacked on top of that, happy to avoid that!

I think a manual close option would work perfectly. As for which type would be best, we should probably choose the nicest solution for where we expect the majority of users to connect from and go for the close button if expecting most people to be on Desktop.

**Comment by Tbaut** [comment]
Hey @dj-pundir, yes feel free to work on this. Just to be clear, all the modals should have a cross in the top right hand corner to close it and the behavior to be closed on click should be removed.
