### ISSUE TITLE
Improve the readability of batch proposal review

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#134]
With the addition of batch transactions, we now have more data to contend with and display on the proposal. 

It would be good to improve the readability. For example, this is a proposal in the transaction queue for a batch transaction of two balance transfers: 

<img width="568" alt="Screenshot 2023-05-10 at 4 32 40 PM" src="https://github.com/ChainSafe/Multix/assets/3982665/32abed94-3d8c-40ab-ad13-a2926a27a375">

**Comment by Tbaut** [comment]
Any suggestion on what would make it more readable? like the address on one line or with the usual `AccountDisplay` anything else?

The hard part is that this is generic. so unless there's a specific rule (that's the case for transfers outside of batches) the formatting is generic as well and it may be tricky to handle well all cases. This is yet again an area where I'd like to have real users feedback. If someone is doing batches of transfer regularly, they'd benefit from it. I know the ChaosDao is doing batch referenda voting for instance, but not sure about transfers.

**Comment by asnaith** [comment]
@Tbaut Yeah with it being generic and covering so many different parameters I can see the difficulty. 

That said, without the indentation, it would probably fit nicer in the space that's there, and if we styled each extrinsic with an outline or something it would be easy to see the separation of different extrinsic in the batch. 

The call, method, section and args will probably be present on all batch extrinsics. Perhaps we could display call, method and section data separately and put the "args" content in the main body? 

I created an example of what I mean (I'm no designer though 😄). 

<img width="568" alt="tx_queue" src="https://github.com/ChainSafe/Multix/assets/3982665/747714b9-915d-4f53-b8cb-b33148227d1b">

**Comment by Tbaut** [comment]
I edited the name of this issue to reflect what can actually be done.
Your design adds 2 things
- style better the batch extrinsic (by separating the extrinsics, removing the 0, 1.
- style better the transfer if it's part of an extrinsic (right now, only stand alone transfers are formated nicely. This is a little less prio because very specific.

It's certainly doable though, the first one should definitely be the priority.

**Comment by Tbaut** [comment]
I will close this for now, as I think things have improved a lot already. the overall styling could be improved, but that's not only for batch.
