### ISSUE TITLE
Watch account

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#145]
While we have a hacky way to watch an account using local storage, we should allow to do it using the UI
- Add a Setting menu
- Add a Account Management section
- Show the watched account **signers** and allow to add/remove one
- Only support adding signers for the start, we should have another issue to support adding multisigs
- Make sure we have some metadata associated to the account so that we don't treat it as if we were able to sign with it

Things to test:
- make sure we see the multisigs associated with the watched account
- when an account is removed the query should be fired again without the account
- I shouldn't be able to sign/review a proposal if I only have a watched account

**Comment by sweetpea22** [comment]
> Show the watched account signers and allow to add/remove one

What do you mean by this exactly? Does this mean owners of multisigs can remove who is watching them?

**Comment by Tbaut** [comment]
No, it's the view only mode. It's live already and available from the settings. You can watch an account or a multisig or a pure proxy, and see the active proposals.
