### ISSUE TITLE
Move Menu bar to the left with icons and grey background

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#163]
We should
- move the current menu to the left
- adapt the design (nuances of gray for selection and background)
- add icons to the menus
- rename the "Home" to Dashboard, and keep the other existing menu entries.

![image](https://github.com/ChainSafe/Multix/assets/33178835/261a55c8-7fcf-49ae-862f-557a77664d69)

keep an virtually invisible top bar for multiproxy and network selection.
![image](https://github.com/ChainSafe/Multix/assets/33178835/83779f63-469f-4ce2-8b82-84b868d6a65d)

The mobile menu should also be adapted and displayed on the left as well.
![image](https://github.com/ChainSafe/Multix/assets/33178835/b19a2394-f1b3-4185-83dd-bebcf4157018)

**Comment by Lykhoyda** [comment]
As the design was changed, we have to adapt the header to the new version:
https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?type=design&node-id=836%3A25990&mode=dev

**Comment by Tbaut** [comment]
Yes, let's close I'll create a new one today.
