### ISSUE TITLE
Adapt buttons to the new design

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#164]
Figma link: https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?type=design&node-id=229-12512&t=cYlBfIExNIk71DWG-0

This goes for
- the clear/add buttons such as the signatory selection/watch account selection
![image](https://github.com/ChainSafe/Multix/assets/33178835/c7017be8-21ea-4fb9-ad2d-a5d8aed4c5ee)
![image](https://github.com/ChainSafe/Multix/assets/33178835/ac6508db-8bcf-45c5-aafe-150e6d2f3164)

- Main/Disabled general buttons
![image](https://github.com/ChainSafe/Multix/assets/33178835/dabb3619-aa23-445f-8f9e-2c6091621a63)

- Send and 3 dots menu (no "Edit" for now)
![image](https://github.com/ChainSafe/Multix/assets/33178835/d149aa57-926a-483d-ae74-f3b95a905fff)

**Comment by sweetpea22** [comment]
note: the link button that says "approve" is not being used right now. i'll update you guys if there is a need for it.

**Comment by Tbaut** [comment]
Thanks, updated
