### ISSUE TITLE
Address with a nickname and identity appears twice in drop down selector

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#174]
**Description**

If an address has been given a nickname but also has an on-chain identity set then the address will appear twice in the drop-down selector

**Prerequisites**

Have an existing multisig

**Steps To Reproduce**

Add clear steps on how to reproduce the bug

1. Go to Multix at 'https://multix.chainsafe.io/'
2. Click on "settings"
3. Add an account that already has an on-chain identity (`DCZyhphXsRLcW84G9WmWEXtAA8DKGtVGSFZLJYty8Ajjyfa`) and give it a nickname
4. Browse dropdown options

**Expected Behaviour**
I would expect the on-chain identity to take precedence over the nickname and for it to only have one entry in the drop-down list. 

**Screenshots / Video**

https://github.com/ChainSafe/Multix/assets/3982665/4a01dc66-fc74-41e5-adae-d249de2c2afb

**Test Host Specifics:**

- Not OS or browser-specific

**Comment by Tbaut** [comment]
So this is linked with identity display, and the issue is happening with any names, not only the watched ones.
We can probably show the set name rather than the identity. This is something that was already done, and I reverted it.
