### ISSUE TITLE
Update title when addresses are being actively watched

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#175]
When there are addresses being actively tracked, "Watched" makes more sense than "Watch" in this context: 

<img width="673" alt="Screenshot 2023-05-23 at 1 30 09 PM" src="https://github.com/ChainSafe/Multix/assets/3982665/757e317e-1574-434d-b800-c5a26a26dbf8">

It would be good to adjust the title depending on the context of whether there are any addresses being actively watched or not.

**Comment by Tbaut** [comment]
oh sorry, that's done as it was a super small thing.
