### ISSUE TITLE
User cannot create a new multisig

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#178]
**Description**
It's currently not possible to fully complete the multisig creation with multix, the UI does not refresh after the initial signing to create and if you refresh the browser manually after 30 seconds then still no pure, multisig or transaction queue is displayed

**Steps To Reproduce**

1. Go to Multix at 'https://multix.chainsafe.io/'
2. Click on 'Create one' or 'New Multisig'
3. Add two signatories (doesn't matter how many)
4. Click Next, Next again and then create
5. Sign the wallet extension 
6. Observe that multix says the multisig is being created but there's no refresh and after refreshing manually there is no new data state

**Expected Behaviour**
User should be able to complete the creation flow

**Console Error**
None visible

**Screenshots / Video**

<img width="1437" alt="Screenshot 2023-05-25 at 2 17 58 PM" src="https://github.com/ChainSafe/Multix/assets/3982665/36d1a515-f6e4-4b9a-9b0a-d2598272dc62">

**Test Host Specifics:**

- Not OS or extension, browser-specific

**Comment by Tbaut** [comment]
indexer issue. Rococo was down unfortunately.
