### ISSUE TITLE
Use the same size drop down inputs in the navigation bar  

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#192]
At the moment the two drop-downs inputs have a slightly different height

<img width="1277" alt="Screenshot 2023-06-06 at 10 43 09 AM" src="https://github.com/ChainSafe/Multix/assets/3982665/e34bfb8e-395c-4299-8782-f2f4b2e20ef5">

**Comment by Tbaut** [comment]
That one has been triggering my OCD for quite a while already :D I'll make it happen!
