### ISSUE TITLE
Align the delete icons on "Change Multisig" modal

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#194]
As described. It would be a visual improvement if all the delete/trash icons were in alignment 

<img width="611" alt="Screenshot 2023-06-06 at 4 40 31 PM" src="https://github.com/ChainSafe/Multix/assets/3982665/586aecc2-9fbe-4b1c-a1a2-58bb9a41da09">

**Comment by Tbaut** [comment]
This is not as trivial as is sounds, and if you align all the icons to the right, they may end up actually very far from the user name, just because 1 name is long, e.g:
```
name 1                                                   X
super dupper long name that makes the other very far     X
name 3                                                   X
name 4                                                   X
name 5                                                   X
```

One trick is to start with the delete icon, but somehow I find it not as nice. Any other idea?
