### ISSUE TITLE
"Back" and "Next" buttons move unintentionally as the viewport is decreased

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#206]
**Description**
The Back / Next buttons do not stay in a fixed position as the viewport is reduced. 

**Screenshots / Video**

https://github.com/ChainSafe/Multix/assets/3982665/faf272ec-8b10-43d0-b39a-ae7bc0675fae

**Comment by Tbaut** [comment]
TBH I'm not sure why this is a bug? I think that's not really an issue :)

**Comment by asnaith** [comment]
@Tbaut Ok. I just thought It looks janky and I would have expected the buttons to be aligned to the right side and not the middle but we can close this if it's intentional.
