### ISSUE TITLE
Show balance of accounts

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#21]
We should show the free balance of all the important accounts, on the same line:
- Pure proxy
- Multisig

To ease things up we can use `api.derive.balances.account` and `formatBnBalance` already in use in the code base.

**Comment by Arun9650** [comment]
hi I like to work on this issue, can you clarify where do you want to show the balance of accounts 

![image](https://user-images.githubusercontent.com/76466509/233549334-8645b52d-2819-4e26-b884-d381a1db3493.png)

**Comment by Tbaut** [comment]
It should be visible for Pure and Multi accounts. On the right after their name/address.

**Comment by Arun9650** [comment]
is this look ok, in terms of implementing the accounts balance, do i need to also show the balance under the delegate 
![image](https://user-images.githubusercontent.com/76466509/233771406-1c064163-877b-4e19-a1e2-38bcc2623323.png)

**Comment by Tbaut** [comment]
Thanks, we can do something in terms of design, but it's a start.

- the balance should only be visible for the multisig account, not the signatories.
- it should only be visible on the left, not in the transaction list (and it shouldn't replace the name or the address)
- please see the balance implementation, using `formatBnBalance` to show a meaningful information.
