### ISSUE TITLE
More information regarding the deposit and fees when sending a tx

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#248]
> Would be cool to have Multix get the current deposit value and tell you you're too poor by X amount

This is the feedback from someone I helped figuring out why the send modal what displaying the following on Polkadot:
![image](https://github.com/ChainSafe/Multix/assets/33178835/b5fc06da-8ebc-4f72-aad6-6d19492168a2)

BTW Polkadot needs 20 DOT deposit for every multisig proposal (you get it back :|)

**Comment by Tbaut** [comment]
Hi @ElizabethOgbee thank you so much for manifesting your interest. Here are some more info:

The screenshot from the OP is saying that the signer doesn't have enough funds. But it doesn't tell how much is needed, which would be helpful.

This particular warning message comes from https://github.com/ChainSafe/Multix/blob/233333bfd7ea8240a9e9c3fee06fa629cc300d0c/packages/ui/src/components/modals/Send.tsx#L146

The `hasSignerEnoughFunds` is an information extracted from the custom hook `useCheckBalance`. Some of the input comes from `multisigProposalNeededFunds` from the other custom hook `useMultisigProposalNeededFunds`. 

Ideally, this warning message would say
> The "Signing with" account doesn't have the required X to submit the transaction. Note that Y are only reserved and returned upon approval/rejection.

Those X and Y should ideally be added as return values from the hook `useMultisigProposalNeededFunds` and displayed. To display those info, you can get helped by another warning that does more or less the same and use `formatBnBalance` here: https://github.com/ChainSafe/Multix/blob/233333bfd7ea8240a9e9c3fee06fa629cc300d0c/packages/ui/src/pages/Creation/Summary.tsx#L115-L116

You can lean more about the fees needed for multisig calls here https://wiki.polkadot.network/docs/learn-account-multisig#multisig-transactions-with-extrinsic-tab

**Comment by ElizabethOgbee** [comment]
Thanks for the indept explanation. I will start working on it right away and i will drop more comment if i have more questions

**Comment by Tbaut** [comment]
@ElizabethOgbee are you still on it? Since this is getting prioritized, I'd take it unless you're about to submit a PR :pray:

**Comment by Tbaut** [comment]
No answer after a day, I'll make it happen then.
