### ISSUE TITLE
New Design for pure proxy view

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#259]
We want to come close to this:
![image](https://github.com/ChainSafe/Multix/assets/33178835/4c561701-9c76-4504-8d71-9e39588aad22)

Figma: https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?node-id=839%3A27723&mode=dev

- This view is only visible when there is a pure proxy
- we can forget about the circle around the identicon
- if there is no pure proxy, the multisig will be displayed and there will be no such header to start with. See https://github.com/ChainSafe/Multix/issues/167

**Comment by Lykhoyda** [comment]
![Screenshot 2023-07-25 at 12 20 32](https://github.com/ChainSafe/Multix/assets/8141917/dda24a98-ea54-4100-804c-964548c7fdcb)

@Tbaut See overview functionality is not implemented as there is no clear understanding of the view that we are going to show. The Home page was refactored and some components were moved to individual files. Also there is no mobile version of the new header

@asnaith Please take a look if everything works as expected
