### ISSUE TITLE
Rework the network dropdown

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#264]
With the growing amount of parachains being supported, the simple dropdown for networks will soon not suffice.
I propose to switch from a simple select, to something more advanced. for instance what Polkassembly is proposing:
![image](https://github.com/ChainSafe/Multix/assets/33178835/da63b2ce-9216-4e37-971a-1874215b5df2)

Or subscan with a button and Modal:
![image](https://github.com/ChainSafe/Multix/assets/33178835/d9f82789-fe76-4c5d-8592-6aa77e4a3541)

**Comment by Tbaut** [comment]
Also adding to this, there's this annoyance in the current dropdown, noticed by a user
> the clickable area is only the icon and text, not including the margin

https://github.com/ChainSafe/Multix/assets/33178835/2d8e03e0-8847-421e-bdc0-90e423f836b6

**Comment by asnaith** [comment]
Let's include improving this too? 

<img width="224" alt="CleanShot 2023-08-18 at 09 44 45@2x" src="https://github.com/ChainSafe/Multix/assets/3982665/0cae48ac-3290-488e-9f47-a42b2caa9815">

<img width="195" alt="CleanShot 2023-08-18 at 09 45 11@2x" src="https://github.com/ChainSafe/Multix/assets/3982665/aeab52ad-5429-4dea-a97f-aac7b0ac061a">

**Comment by Tbaut** [comment]
Sure

**Comment by Lykhoyda** [comment]
Make sure that the menu fits for the range of screens 900 < 1078 and the menu items are aligned in one line

<img width="469" alt="Screenshot 2023-09-26 at 12 49 58" src="https://github.com/ChainSafe/Multix/assets/8141917/78792e88-7886-415b-9096-4ec5d3160eda">

**Comment by Tbaut** [comment]
The selector can be very small, just the icon even such as https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?node-id=210%3A7442&mode=dev so that we leave space for the rest.
![image](https://github.com/ChainSafe/Multix/assets/33178835/dcf1ab72-9e78-401a-9fe7-2df633ceab7b)
