### ISSUE TITLE
Optimize squid queries

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/Multix#268]
**Description**
Graphql query to fetch all multisigs is quite complex and generates very unoptimized SQL query. To make things worse, when we do subscription, it continuously executes that unoptimized SQL query every 5 seconds. We haven't noticed that before because every network was in it's own database schema which meant there was a lot less rows in tables.
Current grapql query: https://github.com/ChainSafe/Multix/blob/86c486945c2ac4223ab682c68bc0204fd09f43fc/packages/ui/src/queries/multisigsByAccounts.graphql

**Prerequisites**

Regular usage

**Steps To Reproduce**

Open multix

**Expected Behaviour**

Super fast response and optimized query

**Potential Solutions**

### 1. Separate everything into different databases.
 - Pro:
    - "simple" solution that will buy us some time
 - Con:
    - once aquarium introduces billing it will be expensive for us
    - we need to change frontend to query different endpoints for each network

### 2. Optimize query

The following query generates two very optimized and fast sql queries which allows us to get multisig accounts. For delagator/delagatee stuff we would need to jump on a call with whiteboard to challge what we actually need.

```graphql
query MultisigsByAccounts($accountIds: [String!], $watchedAccountIds: [String!]) {
  accountMultisigs(where: { signatory: { id_in: $accountIds } }) {
    multisig {
      address,
      isMultisig,
      isPureProxy,
      signatories {
        id
      }

    }
  }
  accounts(where: {id_in: $watchedAccountIds     AND: { isMultisig_eq: true, OR: { isPureProxy_eq: true } }}) {
      address,
      isMultisig,
      isPureProxy,
      signatories {
        id
      }
  }
}
```

Note: for subscription, we would need to send that as two separate subscription querys.

### 3. Keep same db but generate models for each network

For example on squid side, instead of:
```graphql
type Account @entity {
  id: ID! @index @unique
  address: String!
  multisigs: [AccountMultisig] @derivedFrom(field: "signatory")
  isPureProxy: Boolean @index
  # it's the origin/delegator for another proxy accounts, a pure must have some
  delegatorFor: [ProxyAccount!] @derivedFrom(field: "delegator")
  # it's the delegatee/doing stuff on behalf of another account
  delegateeFor: [ProxyAccount!] @derivedFrom(field: "delegatee")
  isMultisig: Boolean @index
  signatories: [AccountMultisig!] @derivedFrom(field: "multisig")
  threshold: Int
  multisigsCalls: [MultisigCall!] @derivedFrom(field: "multisig")
}

```

we would have:
```graphql
type PolkadotAccount @entity {
  id: ID! @index @unique
  address: String!
  multisigs: [PolkadotAccountMultisig] @derivedFrom(field: "signatory")
  isPureProxy: Boolean @index
  # it's the origin/delegator for another proxy accounts, a pure must have some
  delegatorFor: [PolkadotProxyAccount!] @derivedFrom(field: "delegator")
  # it's the delegatee/doing stuff on behalf of another account
  delegateeFor: [PolkadotProxyAccount!] @derivedFrom(field: "delegatee")
  isMultisig: Boolean @index
  signatories: [PolkadotAccountMultisig!] @derivedFrom(field: "multisig")
  threshold: Int
  multisigsCalls: [PolkadotMultisigCall!] @derivedFrom(field: "multisig")
}

type RococoAccount @entity {
  id: ID! @index @unique
  address: String!
  multisigs: [RococoAccountMultisig] @derivedFrom(field: "signatory")
  isPureProxy: Boolean @index
  # it's the origin/delegator for another proxy accounts, a pure must have some
  delegatorFor: [RococoProxyAccount!] @derivedFrom(field: "delegator")
  # it's the delegatee/doing stuff on behalf of another account
  delegateeFor: [RococoProxyAccount!] @derivedFrom(field: "delegatee")
  isMultisig: Boolean @index
  signatories: [RococoAccountMultisig!] @derivedFrom(field: "multisig")
  threshold: Int
  multisigsCalls: [RococoMultisigCall!] @derivedFrom(field: "multisig")
}
//etc

```
and then in processor we would dynamically load models based on network.
For example:
```typescript
import * as DbModels from "../model"

const Account = DbModels[chainId+"Account"];

await ctx.store.save(new Account({...}));
```

**Comment by Tbaut** [comment]
Thanks, I'll will experiment with 1.
Re 2. in this query, we're loosing a very important information regarding the link between pure proxy and multsig unfortunately.
3 sounds not scalable at all with a lot of overhead and new code for each new parachain (potentially a couple new ones every week).

**Comment by mpetrunic** [comment]
> Thanks, I'll will experiment with 1. Re 2. in this query, we're loosing a very important information regarding the link between pure proxy and multsig unfortunately. But yes, let's talk about it. 3. sounds not generic enough and not scalable with a lot of overhead and new "code" for each new parachain (potentially a couple new ones every week).

Re 2: I definitely think if we talk this trough we can get same amount of information with less complicated queries^^

re 3: Not really, if we do it right, only change would be to copy/paste few models in `schema.graphql` and we don't have to do it for small chains, we can still have single table which contains all the "small"/"other" networks and extract them to the specific table if they become problematic. From database architecture, it would make the most sense as we are never searching across multiple chains at the same time

**Comment by mpetrunic** [comment]
Some actual numbers from analyzing queries:

### Original graphql query translated into SQL
`Seq Scan on account  (cost=0.00..100708.89 rows=475 width=151) (actual time=43.478..69.269 rows=20 loops=1)`

**Execution Time: 121.270 ms**

- notice huge coast
- not using index but doing sequential scan

### Small optimized grapql

```graphql
query MyQuery($accountIds: [String!], $watchedAccountIds: [String!]) {
  accountMultisigs(where: { signatory: { id_in: $accountIds } }) {
    multisig {
      address,
      isMultisig,
      isPureProxy,
      signatories {
        signatory {
          address
        }
      }
			delegateeFor {
          id
          type
          delegator {
            address
            isPureProxy
          }
          delegatee {
            address
            isPureProxy
          }
        }
        delegatorFor {
          id
          type
          delegatee {
            address
            isMultisig
            threshold
            signatories {
              signatory {
                address
              }
            }
          }
        }
    }
  }
  accounts(where: {id_in: $watchedAccountIds     AND: { isMultisig_eq: true, OR: { isPureProxy_eq: true } }}) {
    address
        isMultisig
        isPureProxy
        threshold
        signatories {
          signatory {
            address
          }
        }
        delegateeFor {
          id
          type
          delegator {
            address
            isPureProxy
          }
          delegatee {
            address
            isPureProxy
          }
        }
        delegatorFor {
          id
          type
          delegatee {
            address
            isMultisig
            threshold
            signatories {
              signatory {
                address
              }
            }
          }
        }
  }
}
```

results in two SQL queries with **significantly** lower cost:
`Nested Loop Left Join  (cost=27.86..595.78 rows=4 width=203) (actual time=0.183..1.446 rows=19 loops=1)`
**Execution Time: 1.593 ms**
`Bitmap Heap Scan on account  (cost=12.85..279.18 rows=2 width=151) (actual time=0.184..0.188 rows=1 loops=1)`
**Execution Time: 0.618 ms**

**Comment by Tbaut** [comment]
I've been testing the query and made very small changes to come up with something a tiny bit better for users, without changing the core of it. According to my tests, I should be able to get all the info I had previously:

```graphql
query MyQuery($accountIds: [String!], $watchedAccountIds: [String!]) {
  accountMultisigs(where: {OR: [
    {signatory: {id_in: $accountIds}},
    {signatory: {id_in: $watchedAccountIds}}
  ]}) {
    multisig {
      address
      isMultisig
      isPureProxy
      signatories {
        signatory {
          address
        }
      }
      delegateeFor {
        id
        type
        delegator {
          address
          isPureProxy
        }
      }
      delegatorFor {
        id
        type
        delegatee {
          address
          isMultisig
          threshold
          signatories {
            signatory {
              address
            }
          }
        }
      }
    }
  }
  accounts(where: {
  AND: [
    {id_in: $watchedAccountIds},
    {OR: [
      {isPureProxy_eq: true},
      {isMultisig_eq: true}
    ]}
  ]}) {
    address
    isMultisig
    isPureProxy
    threshold
    signatories {
      signatory {
        address
      }
    }
    delegateeFor {
      id
      type
      delegator {
        address
        isPureProxy
      }
    }
    delegatorFor {
      id
      type
      delegatee {
        address
        isMultisig
        threshold
        signatories {
          signatory {
            address
          }
        }
      }
    }
  }
}
```

**Comment by Tbaut** [comment]
I ended up having even smaller queries.

get all the multisig with a signatory of interrest
```graphql
subscription MultisigsBySignatoriesOrWatched(
  $accountIds: [String!]
  $watchedAccountIds: [String!]
) {
  accountMultisigs(
    where: {
      OR: [
        { multisig: { id_in: $watchedAccountIds } }
        { signatory: { id_in: $accountIds } }
        { signatory: { id_in: $watchedAccountIds } }
      ]
    }
  ) {
    multisig {
      address
      threshold
      signatories {
        signatory {
          address
        }
      }
      delegateeFor {
        type
        delegator {
          address
          isPureProxy
        }
      }
    }
  }
}

```
get all the pure proxies by id
```
subscription PureByIds($pureIds: [String!]) {
  accounts(where: { AND: [{ id_in: $pureIds }, { isPureProxy_eq: true }] }) {
    address
    delegatorFor {
      id
      type
      delegatee {
        address
        isMultisig
        threshold
        signatories {
          signatory {
            address
          }
        }
      }
    }
  }
}

```
