### ISSUE TITLE
Application crash when switching between networks

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#293]
**Description**
It's possible to cause the application to crash if rapidly switching between networks without giving time for the connection to the node to complete. 

**Steps To Reproduce**

Rapidly switch to different networks without waiting for them to complete. 

**Console Error**
[log.txt](https://github.com/ChainSafe/Multix/files/12355859/log.txt)

**Video**

https://github.com/ChainSafe/Multix/assets/3982665/a6e59eb0-bf59-46ea-8bfc-529205b32d3d

**Test Host Specifics: **

- OS: macOS
- Browser: Reproduced in the latest builds of Chrome and Firefox

**Additional context**
I've seen it happen on the main home screen but when I was testing I seemed to be able to reproduce it the most when I was connected and watching an account whilst switching networks on the watch screen (but unsure if this is coincidental).

**Comment by Tbaut** [comment]
it's a duplicate of https://github.com/ChainSafe/Multix/issues/243 isn't it?

**Comment by asnaith** [comment]
@Tbaut Sure is, oops 🤦‍♂️!
