### ISSUE TITLE
Pure header design nits

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#295]
While the design looks good with a name, I find that it looks a little weird with the balance on the left, stuck to the address
![image](https://github.com/ChainSafe/Multix/assets/33178835/e7366363-3a15-48eb-ad59-f87d11692b11)

Do you have any suggestion @sweetpea22 for things we could change to make it more balanced?

**Comment by sweetpea22** [comment]
Yeah that's true. Here are some options we can try: 

1A: If no name, set name to untitled and let people set it by clicking an icon. I'm most in favor of this one personally.
1B: Use a button. 

2A and 2B: put the balance underneath. 
<img width="588" alt="Screen Shot 2023-08-16 at 10 41 22 AM" src="https://github.com/ChainSafe/Multix/assets/47398578/c888a410-17de-4abd-98d0-e6abe8ac8eb7">

**Comment by Tbaut** [comment]
Thank you so much. I think the balance is fine as we have a lot of space on the right in general. I personally prefer the 1A as it looks more consistent visually and a button feels too big there. Also your design definitely has more space between the Balance and the account

**Comment by Tbaut** [comment]
closing in favor of https://github.com/ChainSafe/Multix/issues/305
