### ISSUE TITLE
Add indication of the current selected menu in nav bar

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#302]
User feedback
> the top nav bar doesn't indicate the active tab, and that's confusing

@sweetpea22 maybe you can suggest something?

**Comment by sweetpea22** [comment]
Hi, here's a recommendation, does that look ok? 
btw, the padding of the hover tab matches the height of the account and network input. 
<img width="1160" alt="Screen Shot 2023-08-18 at 5 57 43 PM" src="https://github.com/ChainSafe/Multix/assets/47398578/3b76438a-d20c-44e1-82f4-c024e21a4563">

**Comment by Tbaut** [comment]
Works for me, thank you!

**Comment by dj-pundir** [comment]
Hey @Tbaut  Here are we talking about changing the background color from `Blue` to `White`.
Currently we have below:

<img width="955" alt="image" src="https://github.com/ChainSafe/Multix/assets/61174028/4282cb04-e0e3-4a10-aee8-032b6885692d">

**Comment by Tbaut** [comment]
Hey @dj-pundir this issue should be done either at the same time, or after #260 that specifically talks about the nav bar color change indeed.
