### ISSUE TITLE
Change Help menu entry and reorder the page

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#303]
User feedback
> the help tab is overview tab
> I clicked the see overview with an arrow button and can't figure out how to go back

![image](https://github.com/ChainSafe/Multix/assets/33178835/b2d86807-a7bd-453e-9fb3-759c93d943e0)

I think we should rename the Menu to "Overview", move the actual overview map/diagram that everyone likes to the top of the current `Help` page, and leave the rest of the explanations below

**Comment by lazyfuhrer** [comment]
Assign me @Tbaut

**Comment by Tbaut** [comment]
Sure, feel free to work on this :pray:

**Comment by Tbaut** [comment]
@lazyfuhrer are you still on it?

**Comment by dj-pundir** [comment]
Hey @Tbaut I can work on this one.

One query here you want to change the `Help` page to `Overview` so we have to rename, reference of help to overview in code as well right?

**Comment by Tbaut** [comment]
Hey @dj-pundir, sure that'd be great.
