### ISSUE TITLE
Use the main header for multisigs and pure proxies

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#304]
User feedback:
> the home layout is different for one with and without pure proxy and that's inconsistent. like the new transaction button position is different 

We use a large header currently only when there's a proxy. We should also use it for when there's a solo multisig.

Design: https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?node-id=1005%3A17277&mode=dev
![image](https://github.com/ChainSafe/Multix/assets/33178835/51ec83b0-eeca-49ff-ac75-1ea99f89ae10)

**Comment by asnaith** [comment]
The new header is looking good :)

It kind of makes the pre-existing section seem strange though (two new transaction buttons etc). 

I'm not sure what the solution should be. If we replace with "controlled by" (same as we show when the pure is selected) we'd still be showing the multisig identicon twice. 

![CleanShot 2023-09-12 at 16 40 48@2x](https://github.com/ChainSafe/Multix/assets/3982665/0de6b915-51c1-4603-adb8-4c8f7d7deddd)
