### ISSUE TITLE
Amend the main account dropdown behavior

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#308]
Right now, when we change networks, the Multiproxy selector is still visible until the new are set.
We should:
- clear the list of multiproxy on network switch
- show when we're looking for multiproxies (this is displayed on the home, but not in other pages)
- ~~redirect to the home when this resolves whether or not there's something in the list~~ edit: probably not a good idea

**Comment by asnaith** [comment]
The multisigs / pures are being cleared and refreshed on network switch and the loading spinner is working nicely :) 

Just a couple of issues:

- Re-direct to home when the network resolves is not working for me (the issue implies this should be happening).

- Some nav links are being pushed underneath others

<img width="1279" alt="CleanShot 2023-08-28 at 13 18 30@2x" src="https://github.com/ChainSafe/Multix/assets/3982665/d520c01b-903d-48fb-aad7-95065cdae666">
