### ISSUE TITLE
Character overflow for multisig names

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#31]
Multisig name and account name needs a character limit, also if you create a huge multisig name it breaks out of the layout on the review screen (large account name are ok because they get truncated).

**Comment by asnaith** [comment]
Hey @Tbaut, yeah it's still happening. I could enter one with 418 characters. 

<img width="1424" alt="Screenshot 2023-03-20 at 5 04 52 PM" src="https://user-images.githubusercontent.com/3982665/226491469-b3e127c0-e60b-4bf8-b1fe-e3ca3e1d71d9.png">

**Comment by Tbaut** [comment]
Weird, I checked it. That's probably a browser incompatibility. I tested on Firefox. I don't contraint the number of char, I'll do it, but it's wrapping for me.
