### ISSUE TITLE
Missing license field in each package.json

### ISSUE THREAD

**Issue by ltfschoen** [ChainSafe/Multix#317]
**Description**
The following files are missing a license field:
* https://github.com/ChainSafe/Multix/blob/main/packages/ui/package.json
* https://github.com/ChainSafe/Multix/blob/main/squid/package.json

**Steps To Reproduce**

Add clear steps on how to reproduce the bug

1. Run `yarn`
2. View output `warning package.json: No license field

**Expected Behaviour**
Add Apache license to those files

**Comment by Tbaut** [comment]
Hey Luke, thanks for the issue. I didn't have the warning with yarn 3.5, (you should run `corepack enable` before building). But it still can't hurt to add it.
