### ISSUE TITLE
Write a Wiki article about how to craft a TX with pjs and submit it with Multix

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#374]
This flow is nowhere near easy enough and requires a walk-though with images.
Try to take screenshots that will age well (e.g by focusing on the windows that matter rather than large screenshots)
It should:
- show in Multix the selection of "from call data"
- show in pjs > extrinsic how to craft an extrinsic and copy the call data
- paste this in Multix, review and send

**Comment by Tbaut** [comment]
It's published here https://github.com/ChainSafe/Multix/wiki/How-to-submit-a-complex-extrinsic-with-Multix if you want to review/edit @asnaith when you have a moment :pray:

**Comment by asnaith** [comment]
@Tbaut Looks good to me. We could elaborate in places but I think most readers will appreciate the conciseness, as it is.
