### ISSUE TITLE
Make the "connect" button of variant "primary"

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#389]
The current color of the "Connect" button lacks sufficient contrast against the background colour and is not unique in comparison to other components in the interface.  Establishing a connection to the dApp is a pre-requisite for most feature interactions other than watch mode. 

The current low contrast can make it difficult for it to stand out as a prominent part of the interface, especially for those with visual impairments. 

If we make it easier for all users to visually distinguish we may increase the attention to this button and increase the chance of users connecting their wallet as one of their first interactions with Multix. 

<img width="339" alt="273064579-8dce769e-146d-429b-b291-551f582fc5ff" src="https://github.com/ChainSafe/Multix/assets/3982665/e81aa627-8014-4053-b57d-a6b113e0b22e">

Acceptance Criteria: The new colour should provide a clear and distinct visual separation from the background and other components, drawing attention and making it easier for all users to identify.

**Comment by Tbaut** [comment]
Regarding the contrast, I think this is sufficient tbh, just checking on https://coolors.co/contrast-checker/18191a-fafcfd it's basically black on basically white :shrug: 
Also all our buttons with "secondary" variant are all like this.

**Comment by asnaith** [comment]
To be clearer of my intention, my idea was to make this button more prominent/noticeable than others. I'll edit the description. 

Make it easier to distinguish, to encourage users to connect to the dApp as one of their first actions.
