### ISSUE TITLE
Improve ux of adding signatories when creating new multisig

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#39]
During multisig creation the next button becomes active once you have added 2 signatories. 

Due to this, when entering the details of 3rd signatory, it's easy to hit the active next link instead of the + button, which then leads to proceeding without fully adding the signatory. This can lead to momentary user confusion on the next page when seeing fewer signatories than expected. 

It would be good to improve the ux here to prevent / reduce the likelihood of that scenario. 

![Screenshot](https://user-images.githubusercontent.com/3982665/224180851-43df1598-c3ac-41a7-8537-8f92c15e7dc9.jpeg)

**Comment by Tbaut** [comment]
I see 2 ways:
- we make the new signatory field different, and not as aligned as it is right now, to make it clear visually that it's not part of the set yet
- we add any valid account on the fly when clicking on "Next"

2 would require some gymnastic that may not be elegant in the code, while 1 isn't straight-forward without a design yet :D

**Comment by asnaith** [comment]
I think making it visually different could be enough here, automatically adding it could also lead to a different set of users becoming confused. 

Or a 3rd option, we could show a modal warning if next is clicked and there's an entered signatory that has not been added.

**Comment by Tbaut** [comment]
I'm not a huge fan of modals in general, and that's an error one, that no-one likes to see. I'll try to find a way with the design to make it obvious, it shouldn't be too hard. Also I think the "+" is too small and easy to forget, clicking the "Next" seem to come naturally.
