### ISSUE TITLE
Appearance of non-existent multisig displayed after switching networks

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#391]
**Description**
When connected to Multix and viewing an on-chain multisig that exists, switching networks causes the addresses to change to the format of the newly selected network, even though that multisig is not present on the newly selected network. The expected message, "No multisig found for your accounts or watched accounts," is only displayed after a manual browser refresh (refer to the attached video).

**Steps To Reproduce**

1. Connect to Multix with an account that has a multisig on the currently selected network.
2. Switch networks to a network where you know there isn't a multisig for that account.
3. Observe that the addresses change to the format of the newly selected network, falsely implying the existence of a multisig.
4. Manually refresh the browser to see the multisig components removed and the expected "no data" state displayed.

**Expected Behavior:**
The message "No multisig found for your accounts or watched accounts" should be displayed immediately when switching to a network if there isn't a multisig present on that network for the connected account.

**Screenshots / Video**
Please refer to the attached video, which demonstrates the issue. It starts on Kusama with a connected account that has no multisig on that network. When switching to Rococo, where a multisig does exist, and then back to Kusama, the display implies the presence of a multisig on Kusama when it doesn't exist. The expected "no data" state is only shown after a manual refresh.

https://github.com/ChainSafe/Multix/assets/3982665/05166b9f-b641-4c8f-b1ff-da3f815d8256

**Comment by Tbaut** [comment]
Hard to reproduce. We should try to find a pattern if any. Maybe check the network tab when this happens and see if a new WS request is fired (it should with new accounts).

**Comment by asnaith** [comment]
Only reproducible on an out of date staging branch, not in prod or anywhere else. Closing for now and will keep an eye out for the behaviour in subsequent testing.
