### ISSUE TITLE
Show the named multisig/proxy in the send modal dropdown

### ISSUE THREAD

**Issue by LernaJ** [ChainSafe/Multix#395]
**Description**
When making transactions, Multix with provide a drop down with a list of signatories but it will not display other multisigs or proxies. It would be convinient to be able to send to multisigs/proxies from the drop down menu.

See screenshots below
![scrend12 47 33_pm_720](https://github.com/ChainSafe/Multix/assets/75752467/8bde5708-9310-43b1-a840-88e7b26208b5)
![screenshot_2023-09-28_at_12 47 27_pm_720](https://github.com/ChainSafe/Multix/assets/75752467/cf1a70a6-c425-4bd9-81cb-72191e716082)

**Steps To Reproduce**

Add clear steps on how to reproduce the bug

1. Go to Multix at 'https://multix.chainsafe.io/'
2. Select the proxy or multisig you wish to send funds from and cick on 'new transaction'
3. When selecting 'send tokens' option you will asked who you want ot send to
4. The list will include other signatories but not multisigs or proxies

**Comment by Tbaut** [comment]
The list only includes the accounts you have in your extension. We could indeed incluse the accounts that have are in the local name registry. Adding the multisigs and pure would be out of scope IMHO because too dynamic.
