### ISSUE TITLE
How to support Joystream?

### ISSUE THREAD

**Issue by bedeho** [ChainSafe/Multix#397]
It would be great to be able to add a chain to this list, we want to use multix for a standalone Substrate chain. How does one do this?

![Screenshot 2023-10-11 at 12 35 30](https://github.com/ChainSafe/Multix/assets/437292/bcb9537f-4ac6-47ce-8ddd-9c155ffc3409)

**Comment by Tbaut** [comment]
Do you run a subsquid archive for this solo chain, or is this chain part of Subsquid archives? if yes, then we can add it very quickly to the list. If no, then this is where things should start. Multix needs an indexer to be this quick and for users to see their multisig right away. We chose Subsquid for this. You need to run an indexer for your chain, and this indexer needs a subsquid archive.

**Comment by bedeho** [comment]
Thank you for the fast answer, so you just need an indexer, not a particular scheme and set of mappings and API to be served?

**Comment by Tbaut** [comment]
That's right, nothing special on the blockchain side, "just" an indexer. If that's for your own needs, you can also very well run it yourself. You can
- Run a subsquid archive https://github.com/subsquid/substrate-gateway
- Run the indexer needed for Multix (see the `/squid` dir in this repo) pointing at the previous archive
- Run the UI (see the `/packages/ui`  dir in Multix) pointing at the previous indexer

**Comment by Tbaut** [comment]
FWIW indexers infra isn't super expensive, but isn't free either, probably about 100$/month so we wouldn't run them for free on the main Multix website.

**Comment by Tbaut** [comment]
I guess we're talking about Joystream (that's my best guess!)? I see that it's part of the archive registry https://github.com/subsquid/archive-registry/blob/43d7b62053e8843e59fd5d34cfd7db2808ca484d/src/chains.ts#L7 then there's an archive for it.

**Comment by bedeho** [comment]
Fantastic! really looking forward to trying this!

**Comment by Tbaut** [comment]
I wrote you on Element, please check

**Comment by bedeho** [comment]
Replied!

**Comment by Tbaut** [comment]
@bedeho we'll add Joystream in the next days. Just so that it's future proof, can you please make sure the Subsquid ppl will also migrate the subsquid archive to the new arrow-squid? Joystream is in their list, but it's not available yet.
https://docs.subsquid.io/substrate-indexing/supported-networks/

**Comment by bedeho** [comment]
Ok, will follow up and let you know.
