### ISSUE TITLE
Multisig name gets repeatedly appended with "old" 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#41]
When going through the process of making a change to the multisig the name of the pre-existing one is appended with "- old". 

However, if the process to remove a signatory fails or is rejected the name remains and will continue to be appended with more "- old" on subsequent attempts. 

![oldoldold](https://user-images.githubusercontent.com/3982665/224188965-4f67a26e-7860-407a-9eae-da06fa81b745.jpeg)

**Comment by Tbaut** [comment]
https://github.com/ChainSafe/Multix/pull/44 addresses it I think, need to check overall the name handling in any case.
