### ISSUE TITLE
Make sure the correct messages are displayed for the right action

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#412]
Create a test for
- first time landing shows what Multix is
- click on connect without an extension installed -> "No extension found" with link
- click on connect without sharing any account -> "No account found"
- click on connect with sharing an account that has no multisig/pure -> "No multisig found"
- watch an account that has no multisig -> "No multisig found"
- same as above but with a connected account  -> "No multisig found"

**Comment by asnaith** [comment]
@Tbaut Can I re-assign this to myself? I started looking at it earlier today. I think I know the changes I need to make

**Comment by Tbaut** [comment]
Sure
