### ISSUE TITLE
Link Deployments to GitHub Releases for Better Measurability?

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#416]
**Description:**

When we merge to the main branch, we initiate a deployment. This enables rapid delivery of features and fixes, something we aim to maintain.

These deployments are not currently tied to any GitHub release. Should we change this? Associating our deployments with GitHub releases will make our release cadency measurable which could be helpful in the future. 

**Why:**

As Multix matures, measurability might be valuable for informed data-driven discussions. This would directly allow us to have data-backed validation of our release cadence. Demonstrating our commitment to a regular release cadence and measured to encourage us to maintain this. 

Additionally :

- Could help with project awareness. It directly ties new releases to new features, this could help users identify or be informed when specific changes are available.

**Comment by asnaith** [comment]
One downside that comes to mind - it would probably be weird to have a new product release when the only merge that happened was new tests

**Comment by Tbaut** [comment]
Yeah I'm on the fence regarding who this is really useful for. I'm all for serving our users and it doesn't sound really useful for them as it stands :)

**Comment by asnaith** [comment]
> Yeah I'm on the fence regarding who this is really useful for. I'm all for serving our users and it doesn't sound really useful for them as it stands :)

Mainly useful for me wanting to measure things 😄

**Comment by Tbaut** [comment]
Closing this, as this won't happen any time soon.
