### ISSUE TITLE
New multisig name is appended with "- pure"

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#42]
When making a multisig change, it looks like the name from the pure is being used for the new multisig name (rather than using the existing, soon to be old, multisig name). This leads to a multisig with “- pure” in the name. 

![pure_in_multisig](https://user-images.githubusercontent.com/3982665/224428555-0d8fa41d-c70e-4d0c-ba4e-31cfce1ded7e.jpeg)

**Comment by Tbaut** [comment]
partly tackled by https://github.com/ChainSafe/Multix/pull/44
