### ISSUE TITLE
Add UI Tests: Wallet Connect feature

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#422]
**Scenario:** Validate that wallet connect sessions can be established, rejected, and disconnected in Multix. 

**Acceptance Criteria:**

- New cypress tests are added, suggestions:
  - [x] can see the default wallet connect state when no wallet connected
  - [x] can see the default wallet connect state when wallet is connected
  - [ ] can see the wrong network warning on wc connection modal
  - [ ] can see the correct accounts on wc connection modal
  - [ ] can successfully establish a wallet connect session
  - [ ] can disconnect from a wallet connect session
  - [ ] can see the wallet connect wiki link
  - [ ] can see error modal if typing incorrect wallet connect key

**Comment by asnaith** [comment]
@Tbaut I think we can only connect to the hydra testnet if running locally or we have a multisig on Polkadot. 

Do you have any thoughts on how we can create a test that fully establishes a session? Also, IIRC we'd need a new wc key each time too.

**Comment by Tbaut** [comment]
Even harder than connecting to a hydra testnet, the connection to another Dapp in an other tab is simply not possible. Testing walletconnect is totally out of the table for now I'd say.

**Comment by Tbaut** [comment]
Closing this as there won't be any way to test this in the foreseeable future

**Comment by asnaith** [comment]
> Closing this as there won't be any way to test this in the foreseeable future

Ah yeah, good call. We have some basic accordion / state inspections and will have to leave it there.
