### ISSUE TITLE
Better info regarding error: linked address can't be found in your accounts or watched accounts

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#435]
as per https://github.com/ChainSafe/Multix/pull/428#issuecomment-1800500803

When users land on an error page because they clicked on a link, but they don't have the extension connected, or they don't wach the account.

> We should probably have a "why do I see this" accordion or something explaining that they landed here with an account selected, that they don't have neither in their Multisig list, nor as watched accounts. And then we can do some check and suggest to connect their accounts if not done or watch the account if not done yet.

**Comment by Lykhoyda** [comment]
@sweetpea22 can we involve you here, to come up with a beautiful error message or suggestion on how it can look like? 😃

**Comment by Tbaut** [comment]
closing as this was effectively never really requested by users.
