### ISSUE TITLE
Solo chain menu options not displayed correctly (WebKit)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#443]
**Description**
Currently the option for "Joystream" in the responsive layout is not displaying correctly, this is so far only reproducible within the Nova App on iOS and Safari on iOS and Safari on macOS in repsonsive layout (see screenshots / video) so seems like a WebKit issue.  

**Steps To Reproduce**

1. Navigate to Multix within Nova app on iOS or within Safari
2. Open the "hamburger" menu to see options
3. Scroll to the "Joystream" option

**Expected Behaviour**
Menu option should be clearly displayed like the others. 

**Screenshots / Video**

https://github.com/ChainSafe/Multix/assets/3982665/01997c69-c0dd-4761-8313-bfe4d4ef0bb2

![menu option in safari](https://github.com/ChainSafe/Multix/assets/3982665/da2c936e-9dc0-4027-926b-afbe43d038aa)

<img width="902" alt="menu option in desktop safari" src="https://github.com/ChainSafe/Multix/assets/3982665/b8cd2b91-8098-47e1-bae6-2f69c23ae72e">

**Test Host Specifics**

- Safari or Nova Wallet mobile app on iOS 17.1.1 
- Safari on macOS using in responsive layout 

**Additional context**
- Cannot reproduce the issue using the web dev tools and responsive layout in other browsers
- Works as intended on Android too

**Comment by Tbaut** [comment]
Oh, it's probably because it's the only one, that is alone in its category? Problem is that it'll be hard to reproduce.
@Lykhoyda can you think about why that would be?

**Comment by Lykhoyda** [comment]
@Tbaut it's reproducible in Safari (although it's strange), here is the PR for the issue https://github.com/ChainSafe/Multix/pull/444
