### ISSUE TITLE
Support KILT Spiritnet

### ISSUE THREAD

**Issue by weichweich** [ChainSafe/Multix#473]
Hi,

I would love to use this UI for the KILT Spiritnet. Would it be possible to add Spiritnet to the supported chains?

**Comment by Tbaut** [comment]
Hello there, thanks a lot for your interest. I'll work on it in the next days. Can you please contact me on Tg or Twitter (I've the sane handle) since there are some small hosting costs I'd like to discuss. 

Leaving this open till it's live

**Comment by Tbaut** [comment]
@weichweich I´m ready to deploy and found some active mulisigs. Let me know if that looks right:
```
    "accounts": [
      {
        "id": "kilt-4oSwk6CpqHDfU9MHUF1stogp8iLwh8CpEBqPQ7LWBemaoxqR",
        "isPureProxy": false,
        "isMultisig": true,
        "address": "4oSwk6CpqHDfU9MHUF1stogp8iLwh8CpEBqPQ7LWBemaoxqR",
        "threshold": 2
      },
      {
        "id": "kilt-4sZ1yyiJnBkMXFMbm5PpF9TeQvbATJQeKJ3paYMW9j7mnYpv",
        "isPureProxy": false,
        "isMultisig": true,
        "address": "4sZ1yyiJnBkMXFMbm5PpF9TeQvbATJQeKJ3paYMW9j7mnYpv",
        "threshold": 2
      },
      {
        "id": "kilt-4sPMk6DgLbaYHaDKWpwFJQVBv3GupqHJRFWngHeALUrv37x9",
        "isPureProxy": false,
        "isMultisig": true,
        "address": "4sPMk6DgLbaYHaDKWpwFJQVBv3GupqHJRFWngHeALUrv37x9",
        "threshold": 2
      }
    ]
```

**Comment by Tbaut** [comment]
Due to the lack of answer here and on element, this deployment will be removed for now :cry:

**Comment by weichweich** [comment]
Sorry! Somehow i completely missed the activity here. :flushed: I'm very sorry.

**Comment by Tbaut** [comment]
@weichweich does that mean you want this to happen? I can re-deploy it shortly

**Comment by weichweich** [comment]
Hi, thanks for the effort. I would like to see KILT supported, but I'm no longer working for KILT, so it would be up to another team member. I forwarded the ticket to them, if they are interested they will reach out.

**Comment by Tbaut** [comment]
Thank, I'll keep this open until someone tell me they want it :)
