### ISSUE TITLE
Name display seems broken (with parent identity?)

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#488]
Check for instance: 158sHoKeq7ZesHMLcp2MkxFQpd7caEW6Rcy1md3AK1fuX8ak
![image](https://github.com/ChainSafe/Multix/assets/33178835/e0a12039-07ff-4224-83d1-ff403387d30a)

**Comment by mabsattar** [comment]
Hi, I would like to work on this.

**Comment by Tbaut** [comment]
@mabsattar there's already a PR I made earlier today, so no need to work on this.
