### ISSUE TITLE
Better way to copy an address, it's not clear right now

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#489]
When the address is displayed, or even with the identicon, it's not clear at all that the address will be copied.
We need UI indicators for this:
- maybe a tooltip above to say "click to copy address"
- maybe an overlay on hover, with the copy icon..

**Comment by asnaith** [comment]
Tooltip or hover would be ok for desktop but perhaps not for mobile? 

I like the copy icon, as more or less anyone who has used a dapp before knows what this is for

![CleanShot 2024-01-29 at 12 02 06@2x](https://github.com/ChainSafe/Multix/assets/3982665/d26318b5-999c-4882-840e-ff1cf2fa1bfa)

We could then perhaps just display a label for a few seconds to say it's been copied?

**Comment by asnaith** [comment]
Hmm actually with the number of identicons that we display that would be a lot of additional icons if we use a copy icon for each...nevermind 😅

**Comment by Tbaut** [comment]
I think a click/tap on the address with a tooltip saying "address copied" would be better. This is really more for desktop for sure.. And not ideal for mobile.
