### ISSUE TITLE
cvxcv

### ISSUE THREAD

**Issue by sajjadakbarii11** [ChainSafe/Multix#498]
**Description**

**Prerequisites**

Add any setup info / environment / account specifics that need to be in place prior to the test

**Steps To Reproduce**

Add clear steps on how to reproduce the bug

1. Go to Multix at 'https://multix.chainsafe.io/'

**Expected Behaviour**

**Console Error**
If possible, please copy/paste or provide a screenshot of the browser console. To do so, press `Ctrl` + `Shift` + `J` (or `Cmd` + `Shift` + `J` on a Mac)

**Screenshots / Video**
If applicable, please add screenshots or video to help explain or demonstrate the problem you are experiencing.

**Test Host Specifics**

- OS: [e.g. Linux Mint 21.1, macOS 13, Windows 11]
- Browser [e.g. Chrome, Safari]
- Version [e.g. 111]
- Wallet [e.g. Polkadot.js, Talisman]

**Additional context**

**Comment by asnaith** [comment]
Hey @sajjadakbarii11, I'm closing this as the template is not filled out and I'm thinking it was perhaps created by mistake.

Please re-open with details if you are aware of an issue with Multix :)
