### ISSUE TITLE
When a multisig has already been named on another network, we don't display the name and rather override it

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#510]
**Description**
I create a multisig M1 on Polkadot, give it a name "M1-name"
I create a multisig on Kusama, with the same signatories, the process asks me for a name, it's "M2-name".

--> we've effectively overriden M1-name with M2-name without our user knowing.

**Solution**
At multisig creation, we should check whether the public key was already stored and if there's a name for the multisig. If there is, we should proceed and pre-fill the field with this name.

**Comment by kashifmanzer** [comment]
@Tbaut  can I work on this?

**Comment by Tbaut** [comment]
Sure

**Comment by kashifmanzer** [comment]
hi @Tbaut i have cloned the repo can you guide me for to the rule for pushing me changes? like should i make fork and work on it or just make a branch nad work on it..
also in which file should i look for to start working.

**Comment by Tbaut** [comment]
I've tackled this issue in #516, you can take a look.
