### ISSUE TITLE
Reject button in another color

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#511]
![image](https://github.com/ChainSafe/Multix/assets/33178835/b3d5154a-d03c-4de4-b0b2-a8a5ebedb53e)

it's at the same place than the approve, and looks the same. It should probably be red.

**Comment by Michael-Obele** [comment]
Hey, @Tbaut, can I work on this?

**Comment by Tbaut** [comment]
Sure, please do :)

**Comment by Michael-Obele** [comment]
@Tbaut  
Please, can you tell me exactly where in the UI this is?

**Comment by Tbaut** [comment]
It's in the signing Modal. If you look for "Reject" with exact word search, you should find it without much noise.

**Comment by Tbaut** [comment]
I implemented the change in #515 already

**Comment by Michael-Obele** [comment]
Thanks for taking care of this!
