### ISSUE TITLE
As a user I want to create a 1-of-x multisig, so that any member of my team can sign a transaction

### ISSUE THREAD

**Issue by Tomen** [ChainSafe/Multix#544]
Tried to create a 1-of-2, but get this error:

![image](https://github.com/ChainSafe/Multix/assets/317186/74fc3971-3f24-4c63-8c68-44e21b3f82a7)

Imo, this is too prohibitive, since it prevents us from representing our team equally.

**Comment by Tbaut** [comment]
This is a blockchain issue. the min threshold is 2. There's nothing Multix can do unfortunately. I you ask the core devs, they'll probably tell you to use a proxy instead.
