### ISSUE TITLE
error in hydration while doing a swap

### ISSUE THREAD

**Issue by muddlebee** [ChainSafe/Multix#571]
**Description**
error in hydration while doing a swap using multix

**Steps To Reproduce**

Add clear steps on how to reproduce the bug

1. Go to Multix at 'https://multix.chainsafe.io/'
2. Connect your wallet
3. Go to Hydration DEX https://app.hydration.net/trade/swap?assetOut=5
4. See error below
![image](https://github.com/user-attachments/assets/2baa691b-9bc5-4472-b9fb-c365b91a32e1)
![image](https://github.com/user-attachments/assets/b153e811-eaea-4dc6-8c56-5d717454e662)

**Expected Behaviour**

**Console Error**
![image](https://github.com/user-attachments/assets/86a76578-b75c-4bc8-85df-d0478cbf0427)

**Test Host Specifics**

- OS: Windows 11
- Browser Chrome
- Version Latest
- Wallet Multix

**Comment by Tbaut** [comment]
I feel like we had this conversation before, but I can't find it. Did the tx appear on Multix still? If it did, and you signed it, then things would work. I need to find a way to not reject this TX for hydration.

**Comment by muddlebee** [comment]
> I feel like we had this conversation before, but I can't find it. Did the tx appear on Multix still? If it did, and you signed it, then things would work. I need to find a way to not reject this TX for hydration.

No it's quite different from our earlier conversation. The txns aren't appearing in the wallet at all, previously atleast it was the txns were being initiated.

**Comment by Tbaut** [comment]
Sorry for the delay, I've tried to reproduce, but I failed.
Here's what I did:
- connect my Multix account with walletConnect. I see this in multix:
![image](https://github.com/user-attachments/assets/71ea0cee-2378-4b7a-ac54-327c59f115d4)
- go to hydration website, make a swap
- the "signing transaction" is loading on Hydration
- the extrinsic is ready to be signed on Multix too


https://github.com/user-attachments/assets/c0507f29-00e7-43f3-8f3b-b14f1e70d9eb

Can you try to delete the walletconnect connection, on Multix, and maybe on Hydration, and do it again?

**Comment by muddlebee** [comment]
@Tbaut followed the instructions like you mentioned. still there's an issue. attaching the video below
multisig wallet address on hydradx : 5D7tybQTk8v7ULfQkizyVQuaDJpJhfgohHZjk5JoQyiwrfWh
https://hydration.subscan.io/account/5D7tybQTk8v7ULfQkizyVQuaDJpJhfgohHZjk5JoQyiwrfWh

https://github.com/user-attachments/assets/b77bb354-6bf2-4042-9d28-4526bb4c3fdb

**Comment by muddlebee** [comment]
I think I get the issue now, most probably because the individual accounts in hydradx don't have the min balance so the error is coming. hmm closing this.. thank you for your support..
#558 waiting for this :)

**Comment by Tbaut** [comment]
I was about to say, you could print the logs on hydration and see there, the fact that they don't send the tx over wallet connect made me think there's something wrong there.
