### ISSUE TITLE
Show more decimal places on the signing proposal modal

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#67]
We currently only show the first 4 numbers after the decimal point which means proposals of 0.00009 will be displayed as "0.0000" (although the correct amount is still sent if it's approved). 

It would be good to expand this to show the lowest supported amount. 

<img width="929" alt="Screenshot 2023-03-28 at 2 52 15 PM" src="https://user-images.githubusercontent.com/3982665/228375691-2a2c4131-3404-48d2-a4a9-c9548b701099.png">

**Comment by Tbaut** [comment]
Moved this to a bug, we shouldn't show 0 if it's not 0. `formatBnBalance` needs to be adapted to cater for this.
say for anything that's lower than 1/10000 we should go as far as the first non 0 digit. For anything else, we can show up to 0 digits after the comma.

e.g
0.000000123 we should show 0.0000001
0.12 we should show 0.1200 or just 0.12 it doesn't really matter.

**Comment by Anurag-Raut** [comment]
could you please tell how can i reproduce it? , I am running client and I cant get past this screen 
![image](https://user-images.githubusercontent.com/102049482/232212462-b4be8726-40f0-4461-a2b9-e1213b6db724.png)

**Comment by Tbaut** [comment]
@Anurag-Raut you need to create a multisig, this needs at least 2 signatories, then you need to make a transactions to send funds.
