### ISSUE TITLE
Show the type of each proxy

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#79]
When we create a pure proxy, it's by default an "Any" proxy.
Now any account can create other types of proxies. This is also supported by Multix, but it's not displayed anywhere.

E.g you can watch a signatory of `DCZyhphXsRLcW84G9WmWEXtAA8DKGtVGSFZLJYty8Ajjyfa` on Kusama (this is the ChaosDAO pure proxy) like `CrbJuFZWjY3yft424EMTY9hdbWoU878DFs74v3a8nNDeKJD` and you will see that there are 2 multisigs behind the pure proxy, one of which has the type "Any", the other "Governance".

The information regarding the type of proxy is available on the indexer in the `ProxyAccount` type.
https://github.com/ChainSafe/Multix/blob/main/squid/schema.graphql#L32

**Comment by Tbaut** [comment]
Now that we have a new design, we can show this info in the multisig details, e.g 
![image](https://github.com/ChainSafe/Multix/assets/33178835/b4a84f22-ecd7-49ae-8095-73e8b3fc2408)

**Comment by bolajahmad** [comment]
Hi, I will pick this up if it's still an issue?

**Comment by bolajahmad** [comment]
Are there information on the expected behavior of the Proxy Type? At what point during the setup process is the Proxy Type being selected?

On the ticket, I found one place where the proxy type needs to be added in the codebase. In [this file exactly](https://github.com/ChainSafe/Multix/blob/main/packages/ui/src/pages/Home/MultisigView.tsx#L35), I will open a pull request to add it in.

**Comment by Tbaut** [comment]
Hey, I'm not sure what you mean by expected behavior of the proxy type. You never select the proxy type. If any, then it's been set externally.

That's right, you found the place where it should be displayed :+1:

**Comment by bolajahmad** [comment]
I am trying to figure out how to create the multisig such that the proxy type is  Governance, or Staking or any other type.

It would be good to test how the other values display also. How does the ProxyType get set externally?

**Comment by bolajahmad** [comment]
I'd like to inroduce a mapping of the ProxyType to String text. This is for readability, we can define

``` 
enum ProxyType {
  Any
  Governance
  NonTransfer
  IdentityJudgement
  CancelProxy
  Auction
  Staking
  SudoBalances
  NominationPools
  Society
  Unknown
}

ProxyEnumToString = {
  NonTransfer: "Non Transfer"
  IdentityJudgement: "Identity Judgement"
  CancelProxy: "Cancel Proxy"
  SudoBalances: "Sudo Balances"
  NominationPools: "Nomination Pools"
}
```

The single string types will remain as is.

**Comment by Tbaut** [comment]
The type of proxy can change unexpectedly, so I think we should only replace the string on the fly, rather than try to support them all.

You can use a util function such that does something like the following
```
str.replace(/[A-Z]/g, function(match, index) {return index === 0 ? match : ` ${match}`})`
```
effectively adding a space before any non starting upper case.

To create different types of proxy to test, you can follow [this guide](https://support.polkadot.network/support/solutions/articles/65000182179-how-to-create-a-proxy-account) but I would simply advise to watch accounts that have proxies such as the ones mentioned in the first post

**Comment by bolajahmad** [comment]
I understand what you are saying. We need to make sure the conversion is future proof. 

I'll review the mapping logic I had for the proxy type values. Thank you also for the separation logic, that will be useful too

**Comment by bolajahmad** [comment]
Is there a default value for the Proxy Type @Tbaut ? For addresses that do not have a proxy, should the proxy type field be hidden?

## Without Proxy
<img width="491" alt="Screenshot 2024-01-29 at 10 36 42" src="https://github.com/ChainSafe/Multix/assets/56865496/5e47dbb0-75c2-4ea3-8138-f5d473328b60">

## With Proxy
<img width="632" alt="Screenshot 2024-01-29 at 10 55 28" src="https://github.com/ChainSafe/Multix/assets/56865496/e9a55a0c-b921-4284-8378-32d6ef5a2150">

**Comment by Tbaut** [comment]
yes, it shouldn't be there if it's not a proxy
