### ISSUE TITLE
Notification toasts are displayed on top of each other

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#83]
**Description**
When several notification toasts are displayed, they are overlaying each other

**Steps To Reproduce**

Add clear steps on how to reproduce the bug

1. Go to Multix at 'https://multix.chainsafe.io/'
2. Initiate a balance transfer
3. When prompted to sign the extrinsic with the extension, cancel it. This will create a toast with the status "error". Toasts error are set to not auto-disappear, this is fine https://github.com/ChainSafe/Multix/blob/867fe5a5f52ea1f3477ce261eb8ef567048c6eaa/ui/src/components/ToastBar.tsx#L29-L30
4. Now if you don't click on the small cross to close it, any other toast will appear on top of it.

Bellow is a screenshot with a long error toast, and a "Tx broadcasted" toast on top of it.

**Expected Behaviour**
the toasts should ideally stack on top of each other.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/33178835/231721951-359089d8-12bc-433f-b630-579b5b7e0e63.png)

**Comment by dj-pundir** [comment]
Hey @Tbaut  Let me know if I can help you with this. Thanks!!

**Comment by Tbaut** [comment]
Sure, thanks :)

**Comment by dj-pundir** [comment]
Hey @Tbaut  It is not possible to stack the chart with MUI Snackbar. Though they are working on it, once its done we will be able to do that
https://github.com/mui/material-ui/pull/31991

Alternative of this we can use which most of the user used and it seems an alternative by looking at the number of downloads:
https://www.npmjs.com/package/notistack

The original issue of stacking is here
https://github.com/mui/material-ui/issues/1824

Thanks!!

**Comment by Tbaut** [comment]
Notistack is mentioned in the MUI doc yes: https://mui.com/material-ui/react-snackbar/#complementary-projects
We should either use it, or make it work anyhow.

**Comment by dj-pundir** [comment]
Hey @Tbaut I have created customized toast. Here is the sample. Let me know if it works for you. 

[screen-recorder-tue-may-02-2023-17-59-29.webm](https://user-images.githubusercontent.com/61174028/235667194-6c6b9f63-4916-424a-a713-20e049eb8f5c.webm)

It uses MUI Alert where we have 4 options for toast colors. Please check here http://127.0.0.1:3333/create?network=rococo

**Comment by dj-pundir** [comment]
Hey @Tbaut I have come with a solution where i have used old logic to generate the toast but using `notistack `as a base so the look and feel will be same for toast but its stacked up the toasts. Thanks!!

![image](https://user-images.githubusercontent.com/61174028/236869808-da04299a-b806-4bee-89da-dc9ec56e428d.png)
